### ISSUE TITLE
Support status

### ISSUE THREAD

**Issue by fcantournet** [flant/yandex-cloud-controller-manager#12]
Hello :wave: 

I was wondering what the status of the CCM is : is this sanctionned at all by Yandex Cloud ?
Are there any plans, or have there been any attempts to work with Yandex to collaborate on this ?

Since Yandex has a managed kubernetes product now I imagine that they have a very similar project somewhere.

**Comment by zuzzas** [comment]
Hi!

It's not sanctioned by the Yandex.Cloud, but was once acknowledged by them in the official Yandex.Cloud's Telegram channel. There was no news from the Yandex.Cloud team about open-sourcing their CPI and CSI implementations. That's why we have to work from the outside.
